[[dependency]]
org = "ballerina"
name = "regex"
version = "0.7.0-alpha5"

[[dependency]]
org = "ballerina"
name = "observe"
version = "0.9.0"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.1.0-alpha5"

[[dependency]]
org = "ballerina"
name = "sql"
version = "0.6.0-alpha5"

[[dependency]]
org = "ballerina"
name = "io"
version = "0.6.0-alpha5"

[[dependency]]
org = "ballerinax"
name = "java.jdbc"
version = "0.6.0-alpha5"

[[dependency]]
org = "ballerina"
name = "file"
version = "0.7.0-alpha5"


